.TH "src/Board.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Board.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Board\&.hpp'\fP
.br
\fR#include 'Colors\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <iomanip>\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <map>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
