.TH "include/Colors.hpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Colors.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <map>\fP
.br
\fR#include <SFML/Graphics/Color\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColors\fP"
.br
.RI "Centralized static utility for color name validation and mapping\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
