.TH "include/Colors.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Colors.hpp \- Declares the \fBColors\fP class which stores the color standards\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <map>\fP
.br
\fR#include <SFML/Graphics/Color\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColors\fP"
.br
.RI "Centralized static utility for color name validation and mapping\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBColors\fP class which stores the color standards\&. 

Throughout the project seven standard colors and an additional eighth neutral color are commonly referencedand this class standarizes the use of the colors to allow for flexibilty if additional colors are added or removed later\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
