.TH "include/CommandConsole.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CommandConsole.hpp \- Declares the \fBCommandConsole\fP class which allows for user IO\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'Board\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandConsole\fP"
.br
.RI "In-game text console handling user command input, output history, and paging\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBCommandConsole\fP class which allows for user IO\&. 

A key factor in the functionality of the program at whole is allowing the user to interact and receive output\&. This is done through the command console which only handles IO and passes all commands to the \fBGame\fP class to process\&.

.PP
\fBSee also\fP
.RS 4
\fBBoard\fP, \fBRenderer\fP, \fBGame\fP
.RE
.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
