.TH "include/CommandConsole.hpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CommandConsole.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <queue>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'Board\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommandConsole\fP"
.br
.RI "In-game text console handling user command input, output history, and paging\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
