.TH "include/Company.hpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Company.hpp \- Declares the \fBCompany\fP class representing a business entity or player faction\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompany\fP"
.br
.RI "Represents a company, corporation, or in-game faction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBCompany\fP class representing a business entity or player faction\&. 

The \fBCompany\fP class encapsulates the identifying information of a corporate or player-controlled entity within the game\&. Each company is characterized by a unique name and symbol, which may be used for display, ownership marking, or data serialization\&.

.PP
\fBSee also\fP
.RS 4
\fBTile\fP, \fBBoard\fP
.RE
.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
