.TH "include/CubeCoord.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/CubeCoord.hpp \- Defines cube coordinates and hashing utilities for hex-grid operations\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCubeCoord\fP"
.br
.RI "Represents a position in a cube coordinate system\&. "
.ti -1c
.RI "struct \fBCubeCoordHash\fP"
.br
.RI "Hash functor for \fBCubeCoord\fP, allowing use in unordered containers\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines cube coordinates and hashing utilities for hex-grid operations\&. 

This file provides the \fBCubeCoord\fP structure used to represent positions in a 3D cube coordinate system (commonly used for hexagonal grids) and a custom hash functor to enable their use as keys in unordered containers\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
