.TH "CubeCoord" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CubeCoord \- Represents a position in a cube coordinate system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CubeCoord\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCubeCoord\fP (int x_, int y_, int z_)"
.br
.RI "Constructs a \fBCubeCoord\fP with the specified coordinates\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCubeCoord\fP &other) const"
.br
.RI "Compares two CubeCoords for equality\&. "
.ti -1c
.RI "\fBCubeCoord\fP \fBoperator+\fP (const \fBCubeCoord\fP &other) const"
.br
.RI "Adds two CubeCoords component-wise\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "X-axis coordinate\&. "
.ti -1c
.RI "int \fBy\fP"
.br
.RI "Y-axis coordinate\&. "
.ti -1c
.RI "int \fBz\fP"
.br
.RI "Z-axis coordinate\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a position in a cube coordinate system\&. 

Each cube coordinate satisfies x + y + z = 0 in a hex grid context\&. Provides equality and addition operators for coordinate manipulation\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CubeCoord::CubeCoord (int x_, int y_, int z_)\fR [inline]\fP"

.PP
Constructs a \fBCubeCoord\fP with the specified coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIx_\fP The x coordinate\&. 
.br
\fIy_\fP The y coordinate\&. 
.br
\fIz_\fP The z coordinate\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBCubeCoord\fP CubeCoord::operator+ (const \fBCubeCoord\fP & other) const"

.PP
Adds two CubeCoords component-wise\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The coordinate to add\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The resulting \fBCubeCoord\fP\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIother\fP The coordinate to add\&. 
.RE
.PP
\fBReturns\fP
.RS 4
New \fBCubeCoord\fP representing the sum of the two coordinates\&. 
.RE
.PP
< Component-wise addition\&.
.SS "bool CubeCoord::operator== (const \fBCubeCoord\fP & other) const"

.PP
Compares two CubeCoords for equality\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The coordinate to compare against\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if both coordinates are equal\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIother\fP The coordinate to compare against\&. 
.RE
.PP
\fBReturns\fP
.RS 4
True if all components (x, y, z) are equal\&. 
.RE
.PP
< Return true only if all coordinates match\&.
.SH "Member Data Documentation"
.PP 
.SS "int CubeCoord::x"

.PP
X-axis coordinate\&. 
.SS "int CubeCoord::y"

.PP
Y-axis coordinate\&. 
.SS "int CubeCoord::z"

.PP
Z-axis coordinate\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
