.TH "src/Deck.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Deck.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Deck\&.hpp'\fP
.br
\fR#include 'PathUtils\&.hpp'\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <nlohmann/json\&.hpp>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <random>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
