.TH "include/Deck.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Deck.hpp \- Declares the \fBDeck\fP class used for managing collections of \fBCard\fP objects\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'Card\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeck\fP"
.br
.RI "Represents a collection of cards and provides utility operations for card management\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBDeck\fP class used for managing collections of \fBCard\fP objects\&. 

The \fBDeck\fP class represents a container of \fBCard\fP instances\&. It provides functionality for loading cards from JSON files, shuffling, drawing, transferring cards between decks, and querying deck state\&.

.PP
\fBNote\fP
.RS 4
This class assumes that the \fBCard\fP type supports construction from JSON objects\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBCard\fP, \fBPathUtils\fP
.RE
.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
