.TH "src/Game.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Game.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Game\&.hpp'\fP
.br
\fR#include <algorithm>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <random>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <string>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include 'Renderer\&.hpp'\fP
.br
\fR#include 'CommandConsole\&.hpp'\fP
.br
\fR#include 'Colors\&.hpp'\fP
.br
\fR#include 'PathUtils\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr size_t \fBNEUTRAL_COLOR_OFFSET\fP = 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "size_t NEUTRAL_COLOR_OFFSET = 1\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
