.TH "src/main.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Game\&.hpp'\fP
.br
\fR#include 'Company\&.hpp'\fP
.br
\fR#include 'Renderer\&.hpp'\fP
.br
\fR#include 'StartupMenu\&.hpp'\fP
.br
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
