.TH "include/Player.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Player.hpp \- Defines the \fBPlayer\fP class, representing a participant with resources, cards, and a company affiliation\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <unordered_map>\fP
.br
\fR#include 'Company\&.hpp'\fP
.br
\fR#include 'Card\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.RI "Represents a player, managing their resources, cards, score, and associated company\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the \fBPlayer\fP class, representing a participant with resources, cards, and a company affiliation\&. 

Handles resource management, card play/removal, and scoring for an individual player in the game\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
