.TH "src/Player.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Player.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Player\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <algorithm>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
