.TH "include/Renderer.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Renderer.hpp \- Declares the \fBRenderer\fP class responsible for drawing the game board and handling SFML rendering\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <SFML/Graphics\&.hpp>\fP
.br
\fR#include 'Board\&.hpp'\fP
.br
\fR#include 'Tile\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRenderer\fP"
.br
.RI "Handles all visual rendering and window event management for the game\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBRenderer\fP class responsible for drawing the game board and handling SFML rendering\&. 

Handles visual updates of the board, tiles, and console interface within the main SFML window\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
