.TH "src/Renderer.cpp" 3 "Version 1.0" "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Renderer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'Renderer\&.hpp'\fP
.br
\fR#include 'CommandConsole\&.hpp'\fP
.br
\fR#include 'Colors\&.hpp'\fP
.br
\fR#include <cmath>\fP
.br
\fR#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
