.TH "include/StartupMenu.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/StartupMenu.hpp \- Declares the \fBStartupMenu\fP class for initializing and managing the game's main menu\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStartupMenu\fP"
.br
.RI "Manages the initial menu and configuration phase before the main game starts\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBStartupMenu\fP class for initializing and managing the game's main menu\&. 

Handles menu display, player and company setup, configuration persistence, and launching the main game loop\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
