.TH "include/Tile.hpp" 3 "Spotlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Tile.hpp \- Declares the \fBTile\fP class, representing a single board tile that can be owned and colored\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'Company\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTile\fP"
.br
.RI "Represents a single board tile that can be owned by a company and display a color\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declares the \fBTile\fP class, representing a single board tile that can be owned and colored\&. 

Each \fBTile\fP tracks its ownership by a \fBCompany\fP and a color state, providing methods for setting and retrieving this information\&. Tiles default to being unowned and "neutral" in color\&.

.PP
\fBDate\fP
.RS 4
2025-11-06 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuthor\fP
.RS 4
Owen Chilson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Spotlight from the source code\&.
